services:
  mongodb:
    image: mongo:8
    container_name: vanta-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - vanta-mongodb-data:/data/db

volumes:
  vanta-mongodb-data:
